from __future__ import annotations

from pathlib import Path

from opsmindai.agents.onboarding.schemas import OnboardingReport
from opsmindai.tools.github.client import GitHubClient, GitHubCredentialProvider

CONTEXT_ROOT = Path("storage/context_repos")


def _render_markdown(report: OnboardingReport) -> dict[str, str]:
    """Build the structured context-repo artifacts as markdown files."""
    tech = "\n".join(f"- {x}" for x in report.tech_stack) or "- (none detected)"
    services = "\n".join(f"- {x}" for x in report.services) or "- (none detected)"
    questions = "\n".join(f"- [ ] {x}" for x in report.open_questions) or "- (none)"
    warnings = "\n".join(f"- {x}" for x in report.warnings) or "- (none)"

    return {
        "README.md": (
            f"# Context Repo — {report.repo_name}\n\n"
            "Auto-generated by the OpsMindAI onboarding agent. This repo is the "
            "single source of operational context for this service. Humans can "
            "read and edit it; downstream agents (RCA, Release) consume it.\n\n"
            f"- Source repository: {report.source_repo_url or 'n/a'}\n"
            f"- Files committed: project index, tech stack, service map, "
            "open questions, decision tree.\n"
        ),
        "project_index.md": (
            f"# {report.repo_name} — Project Index\n\n"
            f"{report.architecture_summary}\n"
        ),
        "tech_stack.md": f"# Tech Stack\n\n{tech}\n",
        "service_map.md": f"# Service Map\n\n{services}\n",
        "open_questions.md": (
            "# Open Questions (assign to humans)\n\n"
            "These are gaps the agent could not resolve from the codebase alone.\n\n"
            f"{questions}\n"
        ),
        "decision_tree.md": (
            "# Decision Tree\n\n"
            "Operational decisions and their rationale accumulate here as the "
            "team and agents learn the system.\n\n"
            f"## Open risks / warnings\n{warnings}\n"
        ),
    }


class ContextRepoGenerator:
    def __init__(self, credentials: GitHubCredentialProvider | None = None) -> None:
        self.credentials = credentials or GitHubCredentialProvider()

    async def generate(self, customer_id: str, report: OnboardingReport) -> dict:
        """Write artifacts locally AND push them to a real GitHub repo.

        Local write is always done (fast, offline-safe, used by the dashboard).
        GitHub push is attempted when a token is configured; failures degrade to
        local-only with a warning rather than failing onboarding.
        """
        files = _render_markdown(report)

        repo_dir = CONTEXT_ROOT / customer_id
        repo_dir.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            (repo_dir / name).write_text(content, encoding="utf-8")

        result: dict = {
            "local_path": str(repo_dir),
            "context_repo_url": None,
            "context_repo_full_name": None,
            "warnings": [],
        }

        from opsmindai.shared.config import settings

        token = self.credentials.get_token(customer_id)
        host_repo = settings.github_context_repo
        if not token or not host_repo:
            result["warnings"].append(
                "No GitHub token/host repo configured — context written locally only."
            )
            return result

        base_path = f"{settings.context_repo_path_prefix}/{customer_id}"
        client = GitHubClient(token=token)
        try:
            pushed = await client.commit_context_files(
                host_repo_full_name=host_repo,
                base_path=base_path,
                files=files,
                description=f"OpsMindAI context repo for {report.repo_name}",
            )
            result["context_repo_url"] = pushed["html_url"]
            result["context_repo_full_name"] = pushed["repo_full_name"]
            result["committed_files"] = pushed["committed_files"]
        except Exception as exc:  # GitHub down / perms -> partial, keep local
            result["warnings"].append(f"GitHub push failed, kept local copy: {exc}")

        return result
