from __future__ import annotations

from pathlib import Path

from opsmindai.agents.onboarding.schemas import OnboardingReport
from opsmindai.tools.github.client import GitHubClient, GitHubCredentialProvider

CONTEXT_ROOT = Path("storage/context_repos")


def _bullets(items: list[str], empty: str = "- _(none)_") -> str:
    return "\n".join(f"- {x}" for x in items) or empty


def _render_markdown(report: OnboardingReport) -> dict[str, str]:
    """Build the structured context-repo artifacts as markdown files."""
    tech = _bullets(report.tech_stack, "- _(none detected)_")
    services = _bullets(report.services, "- _(none detected)_")
    questions = "\n".join(f"- [ ] {x}" for x in report.open_questions) or "- _(none)_"
    decisions = _bullets(report.key_decisions, "- _(none captured yet)_")
    flows = _bullets(report.data_flows, "- _(no data flows mapped)_")
    risks = _bullets(report.risks, "- _(no risks flagged)_")
    warnings = _bullets(report.warnings)

    if report.components:
        rows = "\n".join(
            f"| `{c.name}` | {c.responsibility or '—'} | {c.tech or '—'} | "
            f"{', '.join(c.dependencies) or '—'} | {c.data_store or '—'} |"
            for c in report.components
        )
        component_table = (
            "| Component | Responsibility | Tech | Depends on | Data store |\n"
            "|---|---|---|---|---|\n" + rows
        )
    else:
        component_table = "_No discrete components detected — likely a single service._"

    files = {
        "README.md": (
            f"# Context Repo — {report.repo_name}\n\n"
            "Auto-generated by the OpsMindAI onboarding agent: the single source of "
            "operational context for this system. Humans read/edit it; the RCA and "
            "Release agents consume it.\n\n"
            f"- **Source repository:** {report.source_repo_url or 'n/a'}\n\n"
            "## Contents\n"
            "- [project_index.md](project_index.md) — architecture overview\n"
            "- [service_map.md](service_map.md) — components and dependencies\n"
            "- [data_flows.md](data_flows.md) — how requests/data move\n"
            "- [tech_stack.md](tech_stack.md)\n"
            "- [business_context.md](business_context.md)\n"
            "- [risks.md](risks.md)\n"
            "- [decision_records.md](decision_records.md)\n"
            "- [open_questions.md](open_questions.md)\n"
        ),
        "project_index.md": (
            f"# {report.repo_name} — Architecture Overview\n\n"
            f"{report.architecture_summary}\n\n"
            f"## Components at a glance\n\n{component_table}\n"
        ),
        "service_map.md": (
            f"# Service Map\n\n## Services\n{services}\n\n"
            f"## Component detail\n\n{component_table}\n"
        ),
        "data_flows.md": f"# Data Flows\n\nHow requests and data move through the system.\n\n{flows}\n",
        "tech_stack.md": f"# Tech Stack\n\n{tech}\n",
        "business_context.md": (
            "# Business Context\n\n"
            f"{report.business_context or '_No business context provided during onboarding._'}\n"
        ),
        "risks.md": (
            "# Operational Risks\n\n"
            "Risks the agent inferred from code, config, and provided context.\n\n"
            f"{risks}\n\n## Scan warnings\n{warnings}\n"
        ),
        "decision_records.md": (
            "# Decision Records\n\n"
            "Key architectural and operational decisions extracted from provided "
            "decision records and transcripts.\n\n"
            f"{decisions}\n"
        ),
        "open_questions.md": (
            "# Open Questions (assign to humans)\n\n"
            "Gaps the agent could not resolve from available evidence.\n\n"
            f"{questions}\n"
        ),
    }
    return files


class ContextRepoGenerator:
    def __init__(self, credentials: GitHubCredentialProvider | None = None) -> None:
        self.credentials = credentials or GitHubCredentialProvider()

    async def generate(self, customer_id: str, report: OnboardingReport) -> dict:
        """Write artifacts locally AND push them to a real GitHub repo.

        Local write is always done (fast, offline-safe, used by the dashboard).
        GitHub push is attempted when a token is configured; failures degrade to
        local-only with a warning rather than failing onboarding.
        """
        files = _render_markdown(report)

        repo_dir = CONTEXT_ROOT / customer_id
        repo_dir.mkdir(parents=True, exist_ok=True)
        # Clear stale artifacts so a re-run never leaves orphaned files behind.
        for old in repo_dir.glob("*.md"):
            if old.name not in files:
                old.unlink()
        for name, content in files.items():
            (repo_dir / name).write_text(content, encoding="utf-8")

        result: dict = {
            "local_path": str(repo_dir),
            "context_repo_url": None,
            "context_repo_full_name": None,
            "warnings": [],
        }

        from opsmindai.shared.config import settings

        token = self.credentials.get_token(customer_id)
        host_repo = settings.github_context_repo
        if not token or not host_repo:
            result["warnings"].append(
                "No GitHub token/host repo configured — context written locally only."
            )
            return result

        base_path = f"{settings.context_repo_path_prefix}/{customer_id}"
        client = GitHubClient(token=token)
        try:
            pushed = await client.commit_context_files(
                host_repo_full_name=host_repo,
                base_path=base_path,
                files=files,
                description=f"OpsMindAI context repo for {report.repo_name}",
            )
            result["context_repo_url"] = pushed["html_url"]
            result["context_repo_full_name"] = pushed["repo_full_name"]
            result["committed_files"] = pushed["committed_files"]
        except Exception as exc:  # GitHub down / perms -> partial, keep local
            result["warnings"].append(f"GitHub push failed, kept local copy: {exc}")

        return result
